#encoded = "ALEXMWXLIEJVMGERPMSREJVMGERPMSRWLEZIFIIREHQMVIHXLVSYKLSYXLMWXSVCJSVEWWCQFSPWSJGSYVEKIERHWXVIRKXLXLIWIMGSRMGERMQEPWLEZITSAIVJYPFSHMIWMRXLIGEXJEQMPCXLICVIWIGSRHMRWMDISRPCXSXMKIVWERHVSEVWXLEXGERFILIEVHJVSQJMZIQMPIWEAECEREHYPXPMSRWGSEXMWCIPPSAKSPHERHNYZIRMPIWLEZIWSQIPMKLXWTSXWXLEXHMWETTIEVAMXLEKISRPCQEPIPMSRWXCTMGEPPCFSEWXQERIWXLIMQTVIWWMZIJVMRKISJPSRKLEMVXLEXIRGMVGPIWXLIMVLIEHW"
encoded = "JRERABFGENATREFGBYBIRLBHXABJGUREHYRFNAQFBQBVNSHYYPBZZVGZRAGFJUNGVZGUVAXVATBSLBHJBHYQAGTRGGUVFSEBZNALBGURETHLVWHFGJNAANGRYYLBHUBJVZSRRYVATTBGGNZNXRLBHHAQREFGNAQVZARIRETBAANTVIRLBHHCARIRETBAANYRGLBHQBJAARIRETBAANEHANEBHAQNAQQRFREGLBHARIRETBAANZNXRLBHPELARIRETBAANFNLTBBQOLRARIRETBAANGRYYNYVRNAQUHEGLBH"
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

for i in range(len(alphabet)):
    decoded = ""

    for l in encoded:
        decoded += alphabet[(alphabet.index(l) + i) % len(alphabet)]
    print("\noffset:", i)
    print(decoded)
